//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SortaKinda.Controllers.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SortaKinda.Controllers.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 允许 的本地化字符串。
        /// </summary>
        internal static string Allow {
            get {
                return ResourceManager.GetString("Allow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按首字母排序 的本地化字符串。
        /// </summary>
        internal static string Alphabetical {
            get {
                return ResourceManager.GetString("Alphabetical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 升序 的本地化字符串。
        /// </summary>
        internal static string Ascending {
            get {
                return ResourceManager.GetString("Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 蓝色 的本地化字符串。
        /// </summary>
        internal static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下 的本地化字符串。
        /// </summary>
        internal static string Bottom {
            get {
                return ResourceManager.GetString("Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收藏品 的本地化字符串。
        /// </summary>
        internal static string Collectable {
            get {
                return ResourceManager.GetString("Collectable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 降序 的本地化字符串。
        /// </summary>
        internal static string Descending {
            get {
                return ResourceManager.GetString("Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不允许 的本地化字符串。
        /// </summary>
        internal static string Disallow {
            get {
                return ResourceManager.GetString("Disallow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可染色 的本地化字符串。
        /// </summary>
        internal static string Dyeable {
            get {
                return ResourceManager.GetString("Dyeable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从后向前填充 的本地化字符串。
        /// </summary>
        internal static string FillFromBottom {
            get {
                return ResourceManager.GetString("FillFromBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绿色 的本地化字符串。
        /// </summary>
        internal static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示帮助文本 的本地化字符串。
        /// </summary>
        internal static string HelpText {
            get {
                return ResourceManager.GetString("HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 忽略 的本地化字符串。
        /// </summary>
        internal static string Ignored {
            get {
                return ResourceManager.GetString("Ignored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物品 ID 的本地化字符串。
        /// </summary>
        internal static string ItemId {
            get {
                return ResourceManager.GetString("ItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物品等级 的本地化字符串。
        /// </summary>
        internal static string ItemLevel {
            get {
                return ResourceManager.GetString("ItemLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物品类型 的本地化字符串。
        /// </summary>
        internal static string ItemType {
            get {
                return ResourceManager.GetString("ItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开配置窗口 的本地化字符串。
        /// </summary>
        internal static string OpenConfigWindow {
            get {
                return ResourceManager.GetString("OpenConfigWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排序选项 的本地化字符串。
        /// </summary>
        internal static string OrderingConfig {
            get {
                return ResourceManager.GetString("OrderingConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 以太化 的本地化字符串。
        /// </summary>
        internal static string Pink {
            get {
                return ResourceManager.GetString("Pink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 紫色 的本地化字符串。
        /// </summary>
        internal static string Purple {
            get {
                return ResourceManager.GetString("Purple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 稀有度 的本地化字符串。
        /// </summary>
        internal static string Rarity {
            get {
                return ResourceManager.GetString("Rarity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 同时为未指定物品槽排序 的本地化字符串。
        /// </summary>
        internal static string ReorderUnsorted {
            get {
                return ResourceManager.GetString("ReorderUnsorted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用后会按照名称首字母排序所有未被指定的物品槽,
        ///除此之外不会再为这些物品槽新增额外的排序选项 的本地化字符串。
        /// </summary>
        internal static string ReorderUnsortedHelp {
            get {
                return ResourceManager.GetString("ReorderUnsortedHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可修理 的本地化字符串。
        /// </summary>
        internal static string Repairable {
            get {
                return ResourceManager.GetString("Repairable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收购价格 的本地化字符串。
        /// </summary>
        internal static string SellPrice {
            get {
                return ResourceManager.GetString("SellPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 为所有物品栏排序 的本地化字符串。
        /// </summary>
        internal static string SortAll {
            get {
                return ResourceManager.GetString("SortAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排序选项 的本地化字符串。
        /// </summary>
        internal static string SortingOptions {
            get {
                return ResourceManager.GetString("SortingOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物品新增时排序 的本地化字符串。
        /// </summary>
        internal static string SortOnItemAdded {
            get {
                return ResourceManager.GetString("SortOnItemAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物品变更时排序 的本地化字符串。
        /// </summary>
        internal static string SortOnItemChanged {
            get {
                return ResourceManager.GetString("SortOnItemChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物品堆叠时排序 的本地化字符串。
        /// </summary>
        internal static string SortOnItemMerged {
            get {
                return ResourceManager.GetString("SortOnItemMerged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物品移动时排序 的本地化字符串。
        /// </summary>
        internal static string SortOnItemMoved {
            get {
                return ResourceManager.GetString("SortOnItemMoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物品移出时排序 的本地化字符串。
        /// </summary>
        internal static string SortOnItemRemoved {
            get {
                return ResourceManager.GetString("SortOnItemRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物品分割时排序 的本地化字符串。
        /// </summary>
        internal static string SortOnItemSplit {
            get {
                return ResourceManager.GetString("SortOnItemSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 职业变更时排序 的本地化字符串。
        /// </summary>
        internal static string SortOnJobChange {
            get {
                return ResourceManager.GetString("SortOnJobChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色登录时排序 的本地化字符串。
        /// </summary>
        internal static string SortOnLogin {
            get {
                return ResourceManager.GetString("SortOnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 区域变更时排序 的本地化字符串。
        /// </summary>
        internal static string SortOnZoneChange {
            get {
                return ResourceManager.GetString("SortOnZoneChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上 的本地化字符串。
        /// </summary>
        internal static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 珍稀 的本地化字符串。
        /// </summary>
        internal static string Unique {
            get {
                return ResourceManager.GetString("Unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 独占 的本地化字符串。
        /// </summary>
        internal static string Untradable {
            get {
                return ResourceManager.GetString("Untradable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 白色 的本地化字符串。
        /// </summary>
        internal static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
    }
}
